/*
MySQL Data Transfer
Source Host: localhost
Source Database: frame
Target Host: localhost
Target Database: frame
Date: 2017/7/12 21:57:40
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for sf_b_common
-- ----------------------------
DROP TABLE IF EXISTS sf_b_common;
CREATE TABLE sf_b_common (
  id bigint(20) NOT NULL auto_increment,
  wf_id bigint(20) default NULL,
  trace_id bigint(20) default NULL,
  dynamic_instance_id bigint(20) default NULL,
  uuid varchar(100)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  a11 varchar(255)  default NULL,
  a12 varchar(255)  default NULL,
  a13 varchar(255)  default NULL,
  a14 varchar(255)  default NULL,
  a15 varchar(255)  default NULL,
  a16 varchar(255)  default NULL,
  a17 varchar(255)  default NULL,
  a18 varchar(255)  default NULL,
  a19 varchar(255)  default NULL,
  a20 varchar(255)  default NULL,
  a21 varchar(255)  default NULL,
  a22 varchar(255)  default NULL,
  a23 varchar(255)  default NULL,
  a24 varchar(255)  default NULL,
  a25 varchar(255)  default NULL,
  a26 varchar(255)  default NULL,
  a27 varchar(255)  default NULL,
  a28 varchar(255)  default NULL,
  a29 varchar(255)  default NULL,
  a30 varchar(255)  default NULL,
  a31 varchar(255)  default NULL,
  a32 varchar(255)  default NULL,
  a33 varchar(255)  default NULL,
  a34 varchar(255)  default NULL,
  a35 varchar(255)  default NULL,
  a36 varchar(255)  default NULL,
  a37 varchar(255)  default NULL,
  a38 varchar(255)  default NULL,
  a39 varchar(255)  default NULL,
  a40 varchar(255)  default NULL,
  a41 varchar(255)  default NULL,
  a42 varchar(255)  default NULL,
  a43 varchar(255)  default NULL,
  a44 varchar(255)  default NULL,
  a45 varchar(255)  default NULL,
  a46 varchar(255)  default NULL,
  a47 varchar(255)  default NULL,
  a48 varchar(255)  default NULL,
  a49 varchar(255)  default NULL,
  a50 varchar(255)  default NULL,
  a51 varchar(255)  default NULL,
  a52 varchar(255)  default NULL,
  a53 varchar(255)  default NULL,
  a54 varchar(255)  default NULL,
  a55 varchar(255)  default NULL,
  a56 varchar(255)  default NULL,
  a57 varchar(255)  default NULL,
  a58 varchar(255)  default NULL,
  a59 varchar(255)  default NULL,
  a60 varchar(255)  default NULL,
  a61 varchar(255)  default NULL,
  a62 varchar(255)  default NULL,
  a63 varchar(255)  default NULL,
  a64 varchar(255)  default NULL,
  a65 varchar(255)  default NULL,
  a66 varchar(255)  default NULL,
  a67 varchar(255)  default NULL,
  a68 varchar(255)  default NULL,
  a69 varchar(255)  default NULL,
  a70 varchar(255)  default NULL,
  a71 varchar(255)  default NULL,
  a72 varchar(255)  default NULL,
  a73 varchar(255)  default NULL,
  a74 varchar(255)  default NULL,
  a75 varchar(255)  default NULL,
  a76 varchar(255)  default NULL,
  a77 varchar(255)  default NULL,
  a78 varchar(255)  default NULL,
  a79 varchar(255)  default NULL,
  a80 longtext ,
  a81 longtext ,
  a82 longtext ,
  a83 longtext ,
  a84 longtext ,
  a85 longtext ,
  a86 longtext ,
  a87 longtext ,
  a88 longtext ,
  a89 longtext ,
  a90 longtext ,
  a91 longtext ,
  a92 longtext ,
  a93 longtext ,
  a94 longtext ,
  a95 longtext ,
  a96 longtext ,
  a97 longtext ,
  a98 longtext ,
  a99 longtext ,
  a100 longtext ,
  a101 longtext ,
  a102 longtext ,
  a103 longtext ,
  a104 longtext ,
  a105 longtext ,
  a106 longtext ,
  a107 longtext ,
  a108 longtext ,
  a109 longtext ,
  a110 longtext ,
  a111 longtext ,
  a112 longtext ,
  a113 longtext ,
  a114 longtext ,
  a115 longtext ,
  a116 longtext ,
  a117 longtext ,
  a118 longtext ,
  a119 longtext ,
  a120 longtext ,
  b01 longtext ,
  b02 longtext ,
  b03 longtext ,
  b04 longtext ,
  b05 longtext ,
  b06 longtext ,
  b07 longtext ,
  b08 longtext ,
  b09 longtext ,
  b10 longtext ,
  d01 double default NULL,
  d02 double default NULL,
  d03 double default NULL,
  d04 double default NULL,
  d05 double default NULL,
  d06 double default NULL,
  d07 double default NULL,
  d08 double default NULL,
  d09 double default NULL,
  d10 double default NULL,
  d11 double default NULL,
  d12 double default NULL,
  d13 double default NULL,
  d14 double default NULL,
  d15 double default NULL,
  d16 double default NULL,
  d17 double default NULL,
  d18 double default NULL,
  d19 double default NULL,
  d20 double default NULL,
  d21 double default NULL,
  d22 double default NULL,
  d23 double default NULL,
  d24 double default NULL,
  d25 double default NULL,
  d26 double default NULL,
  d27 double default NULL,
  d28 double default NULL,
  d29 double default NULL,
  d30 double default NULL,
  MEMO varchar(255)  default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_b_common_child
-- ----------------------------
DROP TABLE IF EXISTS sf_b_common_child;
CREATE TABLE sf_b_common_child (
  id bigint(11) NOT NULL auto_increment,
  uuid varchar(255)  default NULL,
  parentuuid varchar(255)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  a11 varchar(255)  default NULL,
  a12 varchar(255)  default NULL,
  a13 varchar(255)  default NULL,
  a14 varchar(255)  default NULL,
  a15 varchar(255)  default NULL,
  a16 varchar(255)  default NULL,
  a17 varchar(255)  default NULL,
  a18 varchar(255)  default NULL,
  a19 varchar(255)  default NULL,
  a20 varchar(255)  default NULL,
  b01 longtext ,
  b02 longtext ,
  b03 longtext ,
  b04 longtext ,
  b05 longtext ,
  d01 double default NULL,
  d02 double default NULL,
  d03 double default NULL,
  d04 double default NULL,
  d05 double default NULL,
  d06 double default NULL,
  d07 double default NULL,
  d08 double default NULL,
  d09 double default NULL,
  d10 double default NULL,
  MEMO varchar(255)  default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_b_config
-- ----------------------------
DROP TABLE IF EXISTS sf_b_config;
CREATE TABLE sf_b_config (
  id bigint(11) NOT NULL auto_increment,
  uuid varchar(100)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  a11 varchar(255)  default NULL,
  a12 varchar(255)  default NULL,
  a13 varchar(255)  default NULL,
  a14 varchar(255)  default NULL,
  a15 varchar(255)  default NULL,
  a16 varchar(255)  default NULL,
  a17 varchar(255)  default NULL,
  a18 varchar(255)  default NULL,
  a19 varchar(255)  default NULL,
  a20 varchar(255)  default NULL,
  a21 varchar(255)  default NULL,
  a22 varchar(255)  default NULL,
  a23 varchar(255)  default NULL,
  a24 varchar(255)  default NULL,
  a25 varchar(255)  default NULL,
  a26 varchar(255)  default NULL,
  a27 varchar(255)  default NULL,
  a28 varchar(255)  default NULL,
  a29 varchar(255)  default NULL,
  a30 varchar(255)  default NULL,
  b01 longtext ,
  b02 longtext ,
  b03 longtext ,
  b04 longtext ,
  b05 longtext ,
  d01 double default NULL,
  d02 double default NULL,
  d03 double default NULL,
  d04 double default NULL,
  d05 double default NULL,
  d06 double default NULL,
  d07 double default NULL,
  d08 double default NULL,
  d09 double default NULL,
  d10 double default NULL,
  MEMO varchar(255)  default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_b_message
-- ----------------------------
DROP TABLE IF EXISTS sf_b_message;
CREATE TABLE sf_b_message (
  id bigint(11) NOT NULL auto_increment,
  uuid varchar(100)  default NULL,
  eventuuid varchar(100)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  a11 varchar(255)  default NULL,
  a12 varchar(255)  default NULL,
  a13 varchar(255)  default NULL,
  a14 varchar(255)  default NULL,
  a15 varchar(255)  default NULL,
  a16 varchar(255)  default NULL,
  a17 varchar(255)  default NULL,
  a18 varchar(255)  default NULL,
  a19 varchar(255)  default NULL,
  a20 varchar(255)  default NULL,
  a21 varchar(255)  default NULL,
  a22 varchar(255)  default NULL,
  a23 varchar(255)  default NULL,
  a24 varchar(255)  default NULL,
  a25 varchar(255)  default NULL,
  a26 varchar(255)  default NULL,
  a27 varchar(255)  default NULL,
  a28 varchar(255)  default NULL,
  a29 varchar(255)  default NULL,
  a30 varchar(255)  default NULL,
  b01 longtext ,
  b02 longtext ,
  b03 longtext ,
  b04 longtext ,
  b05 longtext ,
  d01 double default NULL,
  d02 double default NULL,
  d03 double default NULL,
  d04 double default NULL,
  d05 double default NULL,
  d06 double default NULL,
  d07 double default NULL,
  d08 double default NULL,
  d09 double default NULL,
  d10 double default NULL,
  MEMO varchar(255)  default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_b_quickcommon
-- ----------------------------
DROP TABLE IF EXISTS sf_b_quickcommon;
CREATE TABLE sf_b_quickcommon (
  id bigint(11) NOT NULL auto_increment,
  uuid varchar(100)  default NULL,
  parentuuid varchar(100)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  a11 varchar(255)  default NULL,
  a12 varchar(255)  default NULL,
  a13 varchar(255)  default NULL,
  a14 varchar(255)  default NULL,
  a15 varchar(255)  default NULL,
  a16 varchar(255)  default NULL,
  a17 varchar(255)  default NULL,
  a18 varchar(255)  default NULL,
  a19 varchar(255)  default NULL,
  a20 varchar(255)  default NULL,
  a21 varchar(255)  default NULL,
  a22 varchar(255)  default NULL,
  a23 varchar(255)  default NULL,
  a24 varchar(255)  default NULL,
  a25 varchar(255)  default NULL,
  a26 varchar(255)  default NULL,
  a27 varchar(255)  default NULL,
  a28 varchar(255)  default NULL,
  a29 varchar(255)  default NULL,
  a30 varchar(255)  default NULL,
  b01 longtext ,
  b02 longtext ,
  b03 longtext ,
  b04 longtext ,
  b05 longtext ,
  d01 double default NULL,
  d02 double default NULL,
  d03 double default NULL,
  d04 double default NULL,
  d05 double default NULL,
  d06 double default NULL,
  d07 double default NULL,
  d08 double default NULL,
  d09 double default NULL,
  d10 double default NULL,
  MEMO varchar(255)  default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_b_smallcommon
-- ----------------------------
DROP TABLE IF EXISTS sf_b_smallcommon;
CREATE TABLE sf_b_smallcommon (
  id bigint(20) NOT NULL auto_increment,
  uuid varchar(100)  default NULL,
  parentuuid varchar(100)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  a11 varchar(255)  default NULL,
  a12 varchar(255)  default NULL,
  a13 varchar(255)  default NULL,
  a14 varchar(255)  default NULL,
  a15 varchar(255)  default NULL,
  a16 varchar(255)  default NULL,
  a17 varchar(255)  default NULL,
  a18 varchar(255)  default NULL,
  a19 varchar(255)  default NULL,
  a20 varchar(255)  default NULL,
  a21 varchar(255)  default NULL,
  a22 varchar(255)  default NULL,
  a23 varchar(255)  default NULL,
  a24 varchar(255)  default NULL,
  a25 varchar(255)  default NULL,
  a26 varchar(255)  default NULL,
  a27 varchar(255)  default NULL,
  a28 varchar(255)  default NULL,
  a29 varchar(255)  default NULL,
  a30 varchar(255)  default NULL,
  a31 varchar(255)  default NULL,
  a32 varchar(255)  default NULL,
  a33 varchar(255)  default NULL,
  a34 varchar(255)  default NULL,
  a35 varchar(255)  default NULL,
  a36 varchar(255)  default NULL,
  a37 varchar(255)  default NULL,
  a38 varchar(255)  default NULL,
  a39 varchar(255)  default NULL,
  a40 varchar(255)  default NULL,
  a41 varchar(255)  default NULL,
  a42 varchar(255)  default NULL,
  a43 varchar(255)  default NULL,
  a44 varchar(255)  default NULL,
  a45 varchar(255)  default NULL,
  a46 varchar(255)  default NULL,
  a47 varchar(255)  default NULL,
  a48 varchar(255)  default NULL,
  a49 varchar(255)  default NULL,
  a50 varchar(255)  default NULL,
  b01 longtext ,
  b02 longtext ,
  b03 longtext ,
  b04 longtext ,
  b05 longtext ,
  b06 longtext ,
  b07 longtext ,
  b08 longtext ,
  b09 longtext ,
  b10 longtext ,
  d01 double default NULL,
  d02 double default NULL,
  d03 double default NULL,
  d04 double default NULL,
  d05 double default NULL,
  d06 double default NULL,
  d07 double default NULL,
  d08 double default NULL,
  d09 double default NULL,
  d10 double default NULL,
  d11 double default NULL,
  d12 double default NULL,
  d13 double default NULL,
  d14 double default NULL,
  d15 double default NULL,
  d16 double default NULL,
  d17 double default NULL,
  d18 double default NULL,
  d19 double default NULL,
  d20 double default NULL,
  MEMO varchar(255)  default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_s_datacode
-- ----------------------------
DROP TABLE IF EXISTS sf_s_datacode;
CREATE TABLE sf_s_datacode (
  id bigint(20) NOT NULL auto_increment,
  UUID varchar(255)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  a11 varchar(255)  default NULL,
  a12 varchar(255)  default NULL,
  a13 varchar(255)  default NULL,
  a14 varchar(255)  default NULL,
  a15 varchar(255)  default NULL,
  a16 varchar(255)  default NULL,
  a17 varchar(255)  default NULL,
  a18 varchar(255)  default NULL,
  a19 varchar(255)  default NULL,
  a20 varchar(255)  default NULL,
  a21 varchar(255)  default NULL,
  a22 varchar(255)  default NULL,
  a23 varchar(255)  default NULL,
  a24 varchar(255)  default NULL,
  a25 varchar(255)  default NULL,
  a26 varchar(255)  default NULL,
  a27 varchar(255)  default NULL,
  a28 varchar(255)  default NULL,
  a29 varchar(255)  default NULL,
  a30 varchar(255)  default NULL,
  b01 longtext ,
  b02 longtext ,
  b03 longtext ,
  b04 longtext ,
  b05 longtext ,
  d01 double default NULL,
  d02 double default NULL,
  d03 double default NULL,
  d04 double default NULL,
  d05 double default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_s_group
-- ----------------------------
DROP TABLE IF EXISTS sf_s_group;
CREATE TABLE sf_s_group (
  id bigint(20) NOT NULL auto_increment,
  UUID varchar(100)  default NULL,
  GROUPID varchar(100)  default NULL,
  GROUPNAME varchar(100)  default NULL,
  GROUPSTATUS varchar(100)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_s_group_role
-- ----------------------------
DROP TABLE IF EXISTS sf_s_group_role;
CREATE TABLE sf_s_group_role (
  id bigint(20) NOT NULL auto_increment,
  GROUPUUID varchar(100)  default NULL,
  ROLEUUID varchar(100)  default NULL,
  USERNAME varchar(100)  default NULL,
  ROLEID varchar(100)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_s_log
-- ----------------------------
DROP TABLE IF EXISTS sf_s_log;
CREATE TABLE sf_s_log (
  id bigint(20) NOT NULL auto_increment,
  UUID varchar(255)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  a11 varchar(255)  default NULL,
  a12 varchar(255)  default NULL,
  a13 varchar(255)  default NULL,
  a14 varchar(255)  default NULL,
  a15 varchar(255)  default NULL,
  a16 varchar(255)  default NULL,
  a17 varchar(255)  default NULL,
  a18 varchar(255)  default NULL,
  a19 varchar(255)  default NULL,
  a20 varchar(255)  default NULL,
  a21 varchar(255)  default NULL,
  a22 varchar(255)  default NULL,
  a23 varchar(255)  default NULL,
  a24 varchar(255)  default NULL,
  a25 varchar(255)  default NULL,
  a26 varchar(255)  default NULL,
  a27 varchar(255)  default NULL,
  a28 varchar(255)  default NULL,
  a29 varchar(255)  default NULL,
  a30 varchar(255)  default NULL,
  b01 longtext ,
  b02 longtext ,
  b03 longtext ,
  b04 longtext ,
  b05 longtext ,
  d01 double default NULL,
  d02 double default NULL,
  d03 double default NULL,
  d04 double default NULL,
  d05 double default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_s_role
-- ----------------------------
DROP TABLE IF EXISTS sf_s_role;
CREATE TABLE sf_s_role (
  id bigint(20) NOT NULL auto_increment,
  UUID varchar(100)  default NULL,
  ROLEID varchar(100)  default NULL,
  ROLENAME varchar(100)  default NULL,
  ROLESTATE varchar(100)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_s_role_perm
-- ----------------------------
DROP TABLE IF EXISTS sf_s_role_perm;
CREATE TABLE sf_s_role_perm (
  id bigint(20) NOT NULL auto_increment,
  UUID varchar(255)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  a11 varchar(255)  default NULL,
  a12 varchar(255)  default NULL,
  a13 varchar(255)  default NULL,
  a14 varchar(255)  default NULL,
  a15 varchar(255)  default NULL,
  a16 varchar(255)  default NULL,
  a17 varchar(255)  default NULL,
  a18 varchar(255)  default NULL,
  a19 varchar(255)  default NULL,
  a20 varchar(255)  default NULL,
  a21 varchar(255)  default NULL,
  a22 varchar(255)  default NULL,
  a23 varchar(255)  default NULL,
  a24 varchar(255)  default NULL,
  a25 varchar(255)  default NULL,
  a26 varchar(255)  default NULL,
  a27 varchar(255)  default NULL,
  a28 varchar(255)  default NULL,
  a29 varchar(255)  default NULL,
  a30 varchar(255)  default NULL,
  b01 longtext ,
  b02 longtext ,
  b03 longtext ,
  b04 longtext ,
  b05 longtext ,
  d01 double default NULL,
  d02 double default NULL,
  d03 double default NULL,
  d04 double default NULL,
  d05 double default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_s_user
-- ----------------------------
DROP TABLE IF EXISTS sf_s_user;
CREATE TABLE sf_s_user (
  id bigint(20) NOT NULL auto_increment,
  UUID varchar(255)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  a11 varchar(255)  default NULL,
  a12 varchar(255)  default NULL,
  a13 varchar(255)  default NULL,
  a14 varchar(255)  default NULL,
  a15 varchar(255)  default NULL,
  a16 varchar(255)  default NULL,
  a17 varchar(255)  default NULL,
  a18 varchar(255)  default NULL,
  a19 varchar(255)  default NULL,
  a20 varchar(255)  default NULL,
  a21 varchar(255)  default NULL,
  a22 varchar(255)  default NULL,
  a23 varchar(255)  default NULL,
  a24 varchar(255)  default NULL,
  a25 varchar(255)  default NULL,
  a26 varchar(255)  default NULL,
  a27 varchar(255)  default NULL,
  a28 varchar(255)  default NULL,
  a29 varchar(255)  default NULL,
  a30 varchar(255)  default NULL,
  b01 longtext ,
  b02 longtext ,
  b03 longtext ,
  b04 longtext ,
  b05 longtext ,
  d01 double default NULL,
  d02 double default NULL,
  d03 double default NULL,
  d04 double default NULL,
  d05 double default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_s_user_group
-- ----------------------------
DROP TABLE IF EXISTS sf_s_user_group;
CREATE TABLE sf_s_user_group (
  id bigint(20) NOT NULL auto_increment,
  USERUUID varchar(100)  default NULL,
  GROUPUUID varchar(100)  default NULL,
  USERNAME varchar(100)  default NULL,
  GROUPID varchar(100)  default NULL,
  GROUPNAME varchar(100)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- Table structure for sf_s_user_role
-- ----------------------------
DROP TABLE IF EXISTS sf_s_user_role;
CREATE TABLE sf_s_user_role (
  id bigint(20) NOT NULL auto_increment,
  USERUUID varchar(100)  default NULL,
  ROLEUUID varchar(100)  default NULL,
  USERNAME varchar(100)  default NULL,
  ROLEID varchar(100)  default NULL,
  a01 varchar(255)  default NULL,
  a02 varchar(255)  default NULL,
  a03 varchar(255)  default NULL,
  a04 varchar(255)  default NULL,
  a05 varchar(255)  default NULL,
  a06 varchar(255)  default NULL,
  a07 varchar(255)  default NULL,
  a08 varchar(255)  default NULL,
  a09 varchar(255)  default NULL,
  a10 varchar(255)  default NULL,
  OWNER varchar(255)  default NULL,
  UPDATER varchar(255)  default NULL,
  UPDATETIME varchar(255)  default NULL,
  EFFECTIVE int(11) default NULL,
  CREATEDAY datetime default NULL,
  UPDATEDAY datetime default NULL,
  UPDATECOUNT double default NULL,
  PRIMARY KEY  (id)
) ;

-- ----------------------------
-- View structure for sf_b_quickcommon_a_view
-- ----------------------------
DROP VIEW IF EXISTS sf_b_quickcommon_a_view;
CREATE  VIEW sf_b_quickcommon_a_view AS select sf_b_quickcommon.id AS id,sf_b_quickcommon.uuid AS uuid,sf_b_quickcommon.parentuuid AS parentuuid,sf_b_quickcommon.a01 AS a01,sf_b_quickcommon.a02 AS a02,sf_b_quickcommon.a03 AS a03,sf_b_quickcommon.a04 AS a04,sf_b_quickcommon.a05 AS a05,sf_b_quickcommon.a06 AS a06,sf_b_quickcommon.a07 AS a07,sf_b_quickcommon.a08 AS a08,sf_b_quickcommon.a10 AS a10,sf_b_quickcommon.a09 AS a09,sf_b_quickcommon.a11 AS a11,sf_b_quickcommon.a12 AS a12,sf_b_quickcommon.a14 AS a14,sf_b_quickcommon.a13 AS a13,sf_b_quickcommon.a15 AS a15,sf_b_quickcommon.a16 AS a16,sf_b_quickcommon.a18 AS a18,sf_b_quickcommon.a17 AS a17,sf_b_quickcommon.a19 AS a19,sf_b_quickcommon.a23 AS a23,sf_b_quickcommon.a21 AS a21,sf_b_quickcommon.a20 AS a20,sf_b_quickcommon.a22 AS a22,sf_b_quickcommon.a24 AS a24,sf_b_quickcommon.a25 AS a25,sf_b_quickcommon.a26 AS a26,sf_b_quickcommon.a27 AS a27,sf_b_quickcommon.a28 AS a28,sf_b_quickcommon.a29 AS a29,sf_b_quickcommon.a30 AS a30,sf_b_quickcommon.OWNER AS OWNER,sf_b_quickcommon.UPDATETIME AS UPDATETIME,sf_b_quickcommon.CREATEDAY AS CREATEDAY,sf_b_quickcommon.UPDATER AS UPDATER,sf_b_quickcommon.EFFECTIVE AS EFFECTIVE,sf_b_quickcommon.UPDATEDAY AS UPDATEDAY,sf_b_quickcommon.UPDATECOUNT AS UPDATECOUNT from sf_b_quickcommon;

-- ----------------------------
-- View structure for sf_b_smallcommon_a_view
-- ----------------------------
DROP VIEW IF EXISTS sf_b_smallcommon_a_view;
CREATE VIEW sf_b_smallcommon_a_view AS select sf_b_smallcommon.id AS id,sf_b_smallcommon.uuid AS uuid,sf_b_smallcommon.parentuuid AS parentuuid,sf_b_smallcommon.a01 AS a01,sf_b_smallcommon.a02 AS a02,sf_b_smallcommon.a03 AS a03,sf_b_smallcommon.a04 AS a04,sf_b_smallcommon.a05 AS a05,sf_b_smallcommon.a06 AS a06,sf_b_smallcommon.a09 AS a09,sf_b_smallcommon.a08 AS a08,sf_b_smallcommon.a07 AS a07,sf_b_smallcommon.a10 AS a10,sf_b_smallcommon.a11 AS a11,sf_b_smallcommon.a12 AS a12,sf_b_smallcommon.a13 AS a13,sf_b_smallcommon.a15 AS a15,sf_b_smallcommon.a14 AS a14,sf_b_smallcommon.a16 AS a16,sf_b_smallcommon.a17 AS a17,sf_b_smallcommon.a18 AS a18,sf_b_smallcommon.a19 AS a19,sf_b_smallcommon.a20 AS a20,sf_b_smallcommon.a21 AS a21,sf_b_smallcommon.a22 AS a22,sf_b_smallcommon.a25 AS a25,sf_b_smallcommon.a24 AS a24,sf_b_smallcommon.a23 AS a23,sf_b_smallcommon.a27 AS a27,sf_b_smallcommon.a26 AS a26,sf_b_smallcommon.a28 AS a28,sf_b_smallcommon.a29 AS a29,sf_b_smallcommon.a30 AS a30,sf_b_smallcommon.OWNER AS OWNER,sf_b_smallcommon.UPDATER AS UPDATER,sf_b_smallcommon.UPDATETIME AS UPDATETIME,sf_b_smallcommon.EFFECTIVE AS EFFECTIVE,sf_b_smallcommon.CREATEDAY AS CREATEDAY,sf_b_smallcommon.UPDATEDAY AS UPDATEDAY,sf_b_smallcommon.UPDATECOUNT AS UPDATECOUNT from sf_b_smallcommon;

-- ----------------------------
-- Records 
-- ----------------------------
